[build]
  publish = "dist"
  command = "nuxt build && nuxt export"
[environment]
  NODE_VERSION = "12.*"
[context.branch-deploy.environment]
  NODE_ENV = "development"
#
#[context.deploy-preview.environment]
#  NODE_ENV = "production"
#
## Branch Deploy context: all deploys that are not from a pull/merge request or
## from the Production branch will inherit these settings.
#[context.branch-deploy]
#  command = "echo branch"
#
#[context.dev]
#  command = "echo 'staging'"
#  base = "staging"
